[build]
  # Build command to compile your React app
  command = "npm run build"
  # Publish directory where the bundled files are output (adjust if using a different folder)
  publish = "dist"

# Ensure JavaScript files are served with the correct MIME type
[[headers]]
  for = "/*.js"
  [headers.values]
    Content-Type = "application/javascript"

# Handle SPA routing: redirect all non-file requests to index.html, but exclude .js files
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  conditions = { "